apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCCvDBYBc5AEoPmxXJWvLjyG4DbhgaaFfNP8Nv5zozKjfh/QglFh+28K7xJWXTulw1WvR/i2VdPXsHQ7F+7NSWasQ6GecNTnxvYkHcn6TdMaWuQpwGk1Kt0hMK44sjq2LEFfBjCXAO3WCexTqADlWwPlHBEJMww9s1OMivCF+cGqIIKh+BXcWTBOQweCDNo5SDwG2rj2Q5dUHbrSXvgYTHk+73CwacF2q6xXFYWfYujbQcMm+1xY+f1IHQkpUonN9xSRNGEIFwPJ01Ub9BX3F2C5URb709qRGOP8qVvfstMZQR2D/O5m+Ql5Kfi1v4sEcX1tg+M2x1FNz0qM8hrN3R0wXerb2I5vQOboM5jmxMwxOdh0eMYrRVBPbHK2yU6tdZuEVFw0S6NAfjNW/A8J8ya3VdeqyzpdSyBflmrcro/iLRuBzyRnRvgiXVSIl6dPfGsGb0mmos83LoUWXkGa0fNz3ar318OQGUcuiRg/hUOYEeBz9PdAiqeNptzdXvEhFmMAmV6SvUHybkpgIdoNFFvubt2I3Tz9cuF4AjVI+DVk4XK4m1IiPinGbDMQRUMxJIWmfGvc9zMhU7i9VOCC0rYS7aFEnSYNJ9gcjy1VVeT4U7RdaJfSPDwFv1/xEe+bdYeFEFn4T01PqT5a2pXOGI1heprNu9+pU7/5LN1lHja47sFc4LmhMV4JVm87C7aCWbWGfivR0axspwp1l8eZAkj5M5RHQGTkCABR0TMyA0c6Y6zVxPw2nvcUEFSCi0xaeSe4mnjf35MBaof76WKwpLQg9e2lbkz1ISRzqI4rV9ROR9IBMGvB9RtVU+3SLpXevSRpnpVMW89kRo4VzW4Hls8e9SZcLxqkGvdTeKnr1UmgbPB5qJ5ReFvPtOiSlPgtzXb/rYn87f9s2nRYbqE8VE4DwuMDM6Kg4wBvk0j6mcHq82RGqJWTT+BB0pM
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
