apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgCayWAPZM9f5f9FxG7qbLwEqBXtwYUPRYU56WDfoUMcZqhWEQLwEKr4ojn1UPGjOCjvyn5/peBYKdY2bUyETZ31fnpI07/SlS9HlOayvLAP0AHr6HR7yDWvRZkzOF//COjrbRz2aaSlyaOxSWkxse7EsPkhZBwgZkky94KF8zMDQpZIXhLmOTZG4VUiKS9qfpFsuq4vgSfnFjB+lN5LIhchACUh37OH/KS7idRZOKgzjDGYxR3YyOxflgNwONcx6GV0I2gPuBHbPrI6bFpmgZ3LLafIVG+ZmHB2tgJD5gPYMZdFmTP8SLs+fgIFGDInFj/hm9KOP7Iv4uQfShZgHueKgHRTKuVNhxT45AaTDpoURifS8xLzdMzIGXhRKOVsFvJUIXLhr43fPFdzThAwW7zWwp0hld6xDJbi8FjVsCiqlzMO7FVLQWQVB+WOISXiX6G+FEu3ueRhmLYWSi0KEaC2Eduq2IgTsg8c+5QT/nlrql9daTKOs1DcrnvKDpRYTOjiuuy4g8LOzIo8GIawL97iKzT0bGcRKWzbPOMJAOcnPwdNwmqPNzVZJTATbsNEzk3uRCcvOBc1y5BJAtf5QsTiYVnRMBfO2F0DcbG9nK7ioFNu3co0tPaqSyXUTMikspDjjL4gng9wCudYrVv+IHhS+y52xZG5f7mKC3LyrJa91Zu2hYL+J9r25G6mwjlev4ep8SusP9uCahhOPxjr69DHf3MCYKEbwOpmxOp2dOm7lJR2158UM/pe
    username: AgCoWxxalgOI6+RHSi5xj9oK/AFTzs3KdA32zo1mQXSStOUC2a9w/brJG0kOboEeAkKjVkAbKYnXZ64tLsYDvvsrWpMYb3ewz7UVTJDg0qBhTxpeh641MAYMSYrTS3Lr2KgSvM5cR5xnbshKrNRu1QRxuncPP/yNVDhH5XjetR6Rt84EtfEWx6NvwU/K/BmKEtoQ5XxwxqDcvg2lcAQ2ccK4XPG7HBn9x3EufPnW8JlJ3PV3zAf8IJq9PumTQXQ1sXwQldNKYD/6Z40qkeZ7cLIvxRDNEHzHWAIDW7cN+CXZwQ/1WcG+oA5N8y4K1rDzaz5schxLYwEYjJDfRxxF9eK/QoiE6iPuA6kqLPePzHASxO1ejOyaml+mtVzPJBI8K/ModQ1Mk8DW2gW0Yep7KJJJI0kEKZN9LtX8U3SXw8E7TWzG3MvbpmL4hrgMYDrUeleQhx8PJATLbVVlvpAOb5/rTuTb/OI6opApRwmNW3ozLTut5kx0q0UgSjObZlq60Zg0JQeQCxEWXTCVWJoQ5F5odBpX69CAHBPP8iYRwk2/yGDuWy8VukXR8coTBQ53N66Y+brdk+r7C+bqQJ/yORc0jqrKByaKy1nTLONkR4jXQET85h3kc6FYJx8Q4Z638vT+ZwPsBkK5pmEOgUiaL23NPPtWto1wZ8mePgUwGwBgDmpYZillY5T/dFeCxE08+un7njJEIds=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
