apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCRYItQN+niwkdnEAEcq74gF9dPvrBuV/oArD5LN5DyeSGZLi/1JYqpajH50YHTLtm1BWQmlLnDvJM6cPUei6AZeH4WoUkHfUWtfbzCHHnDYYR4PaLTMHdRtryy4R/cPckxOZpLwfuABH3+IsXXvjUfXYJ4zUs4vWVYRKnw+yDEnDSctd0g9QSyhCpz3r6K4wVpYzCuiXn2ogFK5ubUZpy1i+tttJlegeU+YYU+N7fYC+0acRwrpJgfxKkmMeupMB7aClDTilLAR6MdJmxCZPtT7N9oNOIa9PXQJU7c3kDPkCSS0dDq8+aE486zf1HYkB2EM01zkVP05tMk1+hPZWhXtvlZ32xV7ot0xS9tVK8DP/yof6qlciC/4o7GP2mIA8B5qCawFJmoQ31GEMFF3nb2qu4mAEGNOhCnb+6vqQs+McjI/eBOltTUq2obhOGqPDTR2pvLf8+bGMYuesSNSFWd3Z8T7+BxMPLlGmCgPBUPQma/Tn6CgS62v8r86NYi3cnM+LcK+IHKd2A7v8hSgvC9Q6hgngLcmokrivE7pma5qG6kTmtUBv1A2YB4RiNye0C1gquMtjLxrDn8T390MnvDzM7jnXvkSxS6QXGLIL0EAmKV++laZti1NYGjD6Pss9qP0H3hD8oJJ0rYvbcOBmSxw6BqwO0UvjaAnLh429RNANJlFz5+MfI7D1nifunTfPmIJm+P7VHXxczD0/+/fuIMnjNPAQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
