apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCPdnfDs0Z0IEcdWeoY915+NMZr/fh0msD8p35zqT7KoMd52MMTvan3ZPd1ZB2rR9Ii7GnI5TRti5xMt0o6Popz56IMe6TZIw8Ccec1ChwnvVkHfJCMIHXtJGu9qRtWiX+b4njQ3MghcLEPVlxeqlEyk0SBSSQxSOmHcWn9fXDxt05V+KmBL0t8PCb53ruN5pbdrmVbQWkFInvjJJxZkei5mBUIt7lvMsFEjABGAl/BDbpyq6YqcsxXEv0n59zgfpSFUgqi9UQSN1cm01d0q62vS9XcYo9UjppMwivdpAfr6sxVRAttoAQ+U8EmQp5xfeY4HIZus0NTrfY32B495SqJa7wNuQjiDFArZmG0PUnaw/sh4X+eJbaZ/0Pxim1wXAt51kCeyHA7SyiDVJSL72HS2K0PvD8D4mtTobYXtq7Z0nt9YpDQuxolGrYr3r6qTApkCi//SP3YY9nIvqoBsqbhMuXfEKng8bQImzq5cr3q09aDm88TOOVGf4lmUxxyZ2FDXu0pk6MxuPCRatB9zAvjx4BbkhnzaSUlgHn3BQoSacf2GAihg3RZyoJbQWYbbWUzB4HoTA4GWigGkZPcOqufiHEY8jtJzeQ03GMtnK42y1K/7j5D0AEo845zRU0+gt0ML6UsqR7DSCT20aWH3W3IrfKC/2nKqPOdTeoWaEU2TvHvLpuoSwYjnp7SySn7Jjq2rrTaaHABF/fZ4Fuof2X5ydBYag==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
