apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBNH3TJ4vXSP9GmQosbJppswJzwH01ulodsy9U97/qyMRfNenTMFJIwS45T7jBkbAYKOxu3bzND9bfNYmaFER7YHr+S4vOdQgju9GplDOdUChaIiXiByB6qYwacHLdqT7rREyHdQRBye+UH1JfKiKhBTAGw/kU+W/IvvPvq7Mg6FnBi10qWT4LXCGHw4vIFukImy9jL/3iAC/WvjXAsk3e+ERTrsVmHrGENlCYdS1jnP3Y98J2s9m8LhFwYPMR2OZgtQa5ey6PkjsG7mgEM+uK7AqYR9D4CA6hmASygQSURYEQ2l0xD1/S2glJy9zlZncEctqXAVB6hkJfNByFg6qpGG3S7gVeL8WTL+jOE9hHI+xXX8LQhENYR+1qeD++3KdkGMzXgM4B7fWAm3SYr3KFPbd+HQURgOuXL/0ZksgTJpzDJPO+dmLngsfGZ4eZU8XIHEjEcA4cVn3xiCxyT3es/CPXCcdQfVtIIR9nd1GrMe9EOVQ9Koc3E3IK1AaasCdwB0IPJlkyVbZhy4djdmR+nEQQsejjbOLkcLGL8yKgh32gcLeblftXQp5RhWeql++6UG6mlYwHfwamU1EpqbdiXwEzjFoHGviAeMtBwfVbBvuzO4K3zD8SbzaziuhXHRKdIdDwThTNMeGcMBBugZ8PiC6RCm8AtHo4Ej+gipOci4cYJZOSoZ+vfvTCfGFIF/wPBUNHBy1sPXhdHcNzNdU7jixFjvw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
