apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBWLxiUB5ffEayPeS66cS2EuOD4IRQJDKpcknZGrops9u2ZXy3J0rPJ3rLBYamer0i6XifxJ1yCYaBDejb29/Xd4vBeM+HMOh6OZFp8WN7rNHxSmkzR3LkyPwNkjNd40gN0DKkUs6C3xPK5/vBH8jTpJDmoYo8b2bwZrJ8ibWpJnDUDurijTFqYwCSN/6wBCt1RVN1tbFrwmsY1lUUbf1Qy8E+0X69uuWjqM8pZvnVOCpB6fXSFr3iBfEtK9IEnvceNgK8BFdWB0M+ZyQOUHz63fM5OdMgzoekSKzanF/aU2ca5lL2Tuo4MlXWLx6PYbENV4pwxZOBqbhgUcRlHtMZkJfS0XGVbVW8FdW55Tyw1MFKH2EyTspPGbkBU1JxO/pBHuohBzzv7vxbUPE23ukgjrD/SJaMuZDJN7sSraTPIJ9unh3rLJ/J+L7jgQewQK1msJHDTxc73jZfK+SzA9s4T99nvr08RPmiD+kDN5PFwTjJlgLExkCExuKRHEod1stso6tryb4vadlTNkSyf7AhSnsXJfdNC+Dtf6w998tQAiknFcUIxz3ksICoDM7oMdBsVD4AQKPY8UMQ7MzotKZmoxpJfrd9nDPNkMkwalne+fUIbVItWFIY7iI/g4IGFVbsmcAL3jJeCgSwEf6uDSd97yhAo2nCITgrS7lRGqXrJkcfObSHQiRQf2rS79oTbQ7qC4fc7sLwqFSFq8csElhH3P4qxUw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
